Updating compass tooltips
CoastalResilienceExplorer/GlobalFloodExplorer pull request #58
Opened 2024-07-02 19:10 UTC by lowriech

2024-07-02 19:15 UTC, gislawill requested changes

2024-07-02 19:15 UTC, gislawill commented on src/components/hover.tsx
> +        // setShow(false)
A little clean up

2024-07-02 19:15 UTC, gislawill commented on src/components/hover.tsx
> +      </div> */}
Can we fully delete this?

2024-07-02 19:15 UTC, gislawill commented on src/compass/compass.js
> +      map.addLayer(layer);
Should this be wrapped in a useEffect? This layer is currently added with every render

2024-07-03 01:00 UTC, lowriech commented on src/compass/compass.js
> +      map.addLayer(layer);
I don't think so, it's just in the function definition.  Unless you're talking about the function being redefined every render?

2024-07-03 01:04 UTC, lowriech commented on src/components/hover.tsx
> +        // setShow(false)
This turns `hover.tsx` into more of a generic action factory.  Not sure if that's a good use case, thoughts?

2024-07-03 02:45 UTC, gislawill commented on src/compass/compass.js
> +      map.addLayer(layer);
Ah you're right, I missed read the parentheses

2024-07-03 02:45 UTC, gislawill approved these changes

2024-07-03 17:31 UTC, merged